run:
  skip-dirs:
    - cmd
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  funlen:
    lines: 100

linters:
  enable-all: true
  disable:
    - dupl
    - errcheck
    - gocyclo
    - govet
    - lll

issues:
  exclude-rules:
    - path: pkg/clustermanager/ssh_communicator.go
      text: "G106: Use of ssh InsecureIgnoreHostKey should be audited"
      linters:
        - gosec
